CREATE TABLE user_games (  
    user_game_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER,
    game_id INTEGER,
    date_created TIMESTAMP DEFAULT now() NOT NULL
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_game FOREIGN KEY (game_id) REFERENCES games (id)
);

